# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

# Replace the '❯' symbol in the prompt with '➜'
# [character] # The name of the module we are configuring is 'character'
# success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
format = """
$os\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$shell\
$character"""

[directory]
# style = "blue"
truncation_length = 100
truncate_to_repo = false
style = " yellow"
format = "[:$path]($style)[$read_only]($read_only_style) "

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
#conflicted = "​"
#untracked = "​"
#modified = "​"
#staged = "​"
#renamed = "​"
#deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"


[shell]
fish_indicator = ''
# powershell_indicator = '_'
# zsh_indicator = "  "
zsh_indicator = " zsh"
# powershell_indicator = " "
powershell_indicator = " pwsh"
cmd_indicator = " "
unknown_indicator = 'mystery shell'
style = 'cyan bold'
disabled = false

[os]
disabled = false
format = "$symbol "

[os.symbols]
Windows = " "
Macos = ""
Ubuntu = " "

[azure]
disabled = false
format = 'on [$symbol($subscription)]($style) '
symbol = 'ﴃ '
style = 'blue bold'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[line_break]
disabled = false
